security:
  referrerPolicy: SECURITY_REFERRER_POLICY,
  hpkp:
    maxAge: SECURITY_HPKP_MAX_AGE,
    pins: SECURITY_HPKP_PINS
idam:
  api_url: IDAM_API_URL
  login_url: IDAM_LOGIN_URL
  web_url: IDAM_AUTHENTICATION_WEB_URL
bar:
  url: BAR_API_URL
certs:
  key: CERTS_KEY
  crt: CERTS_CRT
fee:
  url: FEE_API_URL
  jurisdictionsUrl: FEE_API_JURISDICTIONS_URL
session:
  cookieName: JWT_BAR
e2e:
  frontendUrl: E2E_FRONTEND_URL
  barApiUrl: E2E_BAR_API_URL
  waitForTimeoutValue: E2E_WAIT_FOR_TIMEOUT_VALUE
  waitForActionValue: E2E_WAIT_FOR_ACTION_VALUE
site_api:
  url: BAR_API_URL
secrets:
  bar:
    AppInsightsInstrumentationKey: APPINSIGHTS_INSTRUMENTATIONKEY
    bar-IDAM-CLIENT-SECRET: IDAM_CLIENT_SECRET
