security:
  referrerPolicy: origin
idam:
  client_id: bar_frontend
  client_secret: IDAM_CLIENT_SECRET
  login_url: http://localhost:23443/login
  api_url: http://localhost:23443
session:
  cookieName: BAR
bar:
  url: http://localhost:8080
  defaultPort: 3000
fee:
  url: http://localhost:23443
certs:
   crt: ./dev-certificates/localhost.cert
   key: ./dev-certificates/localhost.key
appInsights:
  instrumentationKey: some-key
